services:
    accounts:
        image: peregrination/accounts:section-06
        container_name: accounts-microservice-s06
        ports:
            - "8080:8080"
        deploy:
          resources:
            limits:
              memory: "700m"
        networks:
            - eazybank
    loans:
      image: peregrination/loans:section-06
      container_name: loans-microservice-s06
      ports:
        - "8090:8090"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
          - eazybank
    cards:
      image: peregrination/cards:section-06
      container_name: cards-microservice-s06
      ports:
        - "9000:9000"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
          - eazybank
networks:
    eazybank:
      driver: bridge